ALTER TABLE "user_profiles"
  ADD COLUMN IF NOT EXISTS "bust_cm" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "underbust_cm" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "waist_cm" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "hips_cm" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "thigh_cm" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "bodice_length_front_cm" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "sleeve_length_cm" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "pant_length_cm" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "inseam_cm" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "shoulder_width_cm" DOUBLE PRECISION;
